=== oxxkart/tecweb/practicas/p12/serviciovod_ep.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT cuenta (perfiles)>
<!ATTLIST cuenta correo CDATA #REQUIRED>

<!ELEMENT genero (titulo+)>
<!ATTLIST genero nombre CDATA #REQUIRED>

<!ELEMENT perfil EMPTY>
<!ATTLIST perfil
usuario CDATA #REQUIRED
idioma CDATA #REQUIRED>

<!ELEMENT titulo (#PCDATA)>
<!ATTLIST titulo
duracion CDATA #REQUIRED>
	
<!ELEMENT perfiles (perfil+)>

<!ELEMENT contenido (peliculas, series)>
<!ELEMENT peliculas (genero+) >
<!ENTITY % region "region (MEX|USA|ESP|ARG|KOR) &#34;USA&#34;">
<!ATTLIST peliculas %region;>

<!ELEMENT series (genero+) >
<!ATTLIST series %region;>
<!ELEMENT CatalogoVod (cuenta, contenido)>

=== oxxkart/tecweb/practicas/p12/serviciovod4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CatalogoVod SYSTEM "C:\xampp\htdocs\Tecnologiasweb\tecweb\practicas\p12\serviciovod_ep.dtd">
<CatalogoVod>
    <cuenta correo="">
        <perfiles>
            <perfil usuario="Rdz Oscar" idioma="español"/>
            <perfil usuario="Rdz Miguel" idioma="español"/>
        </perfiles>
    </cuenta>
    <contenido>
        <peliculas region="USA">
            <genero nombre="Dramas">
                <titulo duracion="1h 45min">Los puentes de madison</titulo>
                <titulo duracion="1h 33min">Siempre a tu lado</titulo>
                <titulo duracion="1h 53min">500 dias sin ella</titulo>
                <titulo duracion="2h 13min">No dejes de mirar</titulo>
            </genero>
            <genero nombre="Romanticas">
                <titulo duracion="2h 23min">Pide al tiempo que vuelva</titulo>
                <titulo duracion="1h 50min">Yo antes de ti</titulo>
                <titulo duracion="1h 39min">La casa del lago</titulo>
                <titulo duracion="2h 6min">El descanso</titulo>
            </genero>
        </peliculas>
        <series region="MEX">
            <genero nombre="Ficcion">
                <titulo duracion="1 temporada">The lord of the rings: Anillos del poder</titulo>
                <titulo duracion="1 temporada">Game of the trones</titulo>
                <titulo duracion="3 temporadas">Titans</titulo>
                <titulo duracion="3 temporadas">Gothic</titulo>
            </genero>
            <genero nombre="Terror">
                <titulo duracion="10 temporada">The Walking dead</titulo>
                <titulo duracion="1 temporadas">The last of us</titulo>
                <titulo duracion="1 temporada">Chapelwaite</titulo>
                <titulo duracion="3 temporadas">Lo que vi</titulo>
            </genero>
        </series>
    </contenido>
</CatalogoVod>
